<a href="https://colab.research.google.com/github/Nniikkoollaass/data-science-HW/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
#3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
n = np.random.randint(1, 11,size=(5,5))
print(n)

[[ 7  4 10  1  2]
 [ 2  3  6  7  1]
 [ 6  7  9  5 10]
 [ 2  4  9  8  4]
 [ 1  5  5  4  7]]


In [6]:
#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
b = np.random.random((4, 4))
print(b)

[[0.33573612 0.11337823 0.50378426 0.22984689]
 [0.34913405 0.94502533 0.31728239 0.45928374]
 [0.95124144 0.80793383 0.58385747 0.88621472]
 [0.35377742 0.20999237 0.25640996 0.57822811]]


In [5]:
#5 Створіть два одновимірних масиви розміром 5,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 10
#та виконайте на них поелементні операції додавання, віднімання та множення.
five_one = np.random.randint(1, 11,size=5)
five_two = np.random.randint(1, 11,size=5)
print(f"First -\n {five_one}")
print(f"Second -\n {five_two}")
print(f"Addition: ->\n {five_one + five_two}")
print(f"Subtraction: ->\n {five_one - five_two}")
print(f"Multiplication: ->\n {five_one * five_two}")

First -
 [ 7 10  8  7  4]
Second -
 [2 9 2 6 2]
Addition: ->
 [ 9 19 10 13  6]
Subtraction: ->
 [5 1 6 1 2]
Multiplication: ->
 [14 90 16 42  8]


In [16]:
#6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
six_one = np.random.randint(1, 10,size=7)
six_two = np.random.randint(1, 10,size=7)
print(f"First -\n {six_one}")
print(f"Second -\n {six_two}")
print(f"Scalar product: ->\n {np.dot(six_one, six_two)}")

First -
 [3 8 5 9 1 1 1]
Second -
 [7 6 6 6 6 6 4]
Scalar product: ->
 169


In [6]:
#7 Створіть дві матриці розміром 2x2 та 2x3,
# заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
seven_one = np.random.randint(1, 11,size=(2,2))
seven_two = np.random.randint(1, 11,size=(2,3))
print(f"First -\n {seven_one}")
print(f"Second -\n {seven_two}")
print(f"Matrix multiplication: ->\n{np.dot(seven_one, seven_two)}")

First -
 [[3 6]
 [8 7]]
Second -
 [[4 9 2]
 [1 8 5]]
Matrix multiplication: ->
[[ 18  75  36]
 [ 39 128  51]]


In [7]:
#8 Створіть матрицю розміром 3x3,
#заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
eight = np.random.randint(1, 11,size=(3,3))
print(eight)
eight_inv = np.linalg.inv(eight)
print(f"Inverse matrix: -> \n{eight_inv}")

[[ 4 10  1]
 [ 7  6  1]
 [ 7  1  5]]
Inverse matrix: -> 
[[-0.14572864  0.24623116 -0.0201005 ]
 [ 0.14070352 -0.06532663 -0.01507538]
 [ 0.1758794  -0.33165829  0.23115578]]


In [14]:
#9 Створіть матрицю розміром 4x4,
# заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
nine = np.random.random((4, 4))
print(nine)
nine_transposed = np.transpose(nine)
print(f"Transposed matrix: -> \n{nine_transposed}")

[[0.11897558 0.62483128 0.20489398 0.40609407]
 [0.54767224 0.9062061  0.35517008 0.66276221]
 [0.69850924 0.96172831 0.83488587 0.4736684 ]
 [0.36416545 0.68794842 0.16888788 0.80671953]]
Transposed matrix: -> 
[[0.11897558 0.54767224 0.69850924 0.36416545]
 [0.62483128 0.9062061  0.96172831 0.68794842]
 [0.20489398 0.35517008 0.83488587 0.16888788]
 [0.40609407 0.66276221 0.4736684  0.80671953]]


In [2]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
ten_matrix = np.random.randint(1, 11,size=(3,4))
print(F"Matrix: ->\n{ten_matrix}")
ten_vector = np.random.randint(1, 11,size=(4))
print(F"Vector: ->\n{ten_vector}")
print(f"Multiplication: ->\n {np.dot(ten_matrix, ten_vector)}")

Matrix: ->
[[ 7  5  6  9]
 [ 6  7  6 10]
 [ 1  3  7  9]]
Vector: ->
[6 4 8 6]
Multiplication: ->
 [164 172 128]


In [3]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3,
# заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
eleven_matrix = np.random.random((2, 3))
print(F"Matrix: ->\n{eleven_matrix}")
eleven_vector = np.random.random((3))
print(F"Vector: ->\n{eleven_vector}")
print(f"Multiplication: ->\n {np.dot(eleven_matrix, eleven_vector)}")

Matrix: ->
[[0.74409631 0.98765398 0.43657266]
 [0.9572765  0.98298798 0.62340168]]
Vector: ->
[0.96940202 0.13374243 0.68311197]
Multiplication: ->
 [1.15164772 1.48530614]


In [9]:
#12 Створіть дві матриці розміром 2x2,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
twelve_matrix = np.random.randint(1, 11,size=(2,2))
print(F"Matrix: ->\n{twelve_matrix}")
twelve_vector = np.random.randint(1, 11,size=(2,2))
print(F"Vector: ->\n{twelve_vector}")
print(f"Elemental multiplication: ->\n {twelve_matrix * twelve_vector}")

Matrix: ->
[[ 7  9]
 [ 6 10]]
Vector: ->
[[10  1]
 [10  5]]
Elemental multiplication: ->
 [[70  9]
 [60 50]]


In [10]:
#13 Створіть дві матриці розміром 2x2,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
thirteen_matrix_one = np.random.randint(1, 11,size=(2,2))
print(F"Matrix one: ->\n{thirteen_matrix_one}")
thirteen_matrix_two = np.random.randint(1, 11,size=(2,2))
print(F"Matrix two: ->\n{thirteen_matrix_two}")
print(f"Multiplication: ->\n {np.dot(thirteen_matrix_one, thirteen_matrix_two)}")

Matrix one: ->
[[ 8 10]
 [ 4  5]]
Matrix two: ->
[[3 5]
 [4 7]]
Multiplication: ->
 [[ 64 110]
 [ 32  55]]


In [11]:
#14 Створіть матрицю розміром 5x5,
#заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
fourteen_matrix = np.random.randint(1, 101,size=(5,5))
print(F"Matrix: ->\n{fourteen_matrix}")
print(F"The sum of matrix elements: ->\n{fourteen_matrix.sum()}")

Matrix: ->
[[39  8 50 92 22]
 [54  1 40 69 49]
 [78 47 41 33 37]
 [13 49 76  5 35]
 [38 16 26 21  4]]
The sum of matrix elements: ->
943


In [12]:
#15 Створіть дві матриці розміром 4x4,
# заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
fifteen_matrix_one = np.random.randint(1, 11,size=(4,4))
print(F"Matrix one: ->\n{fifteen_matrix_one}")
fifteen_matrix_two = np.random.randint(1, 11,size=(4,4))
print(F"Matrix two: ->\n{fifteen_matrix_two}")
print(F"Subtraction of matrices: ->\n{fifteen_matrix_one - fifteen_matrix_two}")

Matrix one: ->
[[2 4 6 6]
 [8 9 6 8]
 [1 8 1 8]
 [4 3 1 7]]
Matrix two: ->
[[ 1  5  7  2]
 [ 5  6  5  1]
 [10  7  9  4]
 [ 7  2  8  1]]
Subtraction of matrices: ->
[[ 1 -1 -1  4]
 [ 3  3  1  7]
 [-9  1 -8  4]
 [-3  1 -7  6]]


In [15]:
#16 Створіть матрицю розміром 3x3,
#заповніть її випадковими дійсними числами в діапазоні від 0 до 1
#та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
sixteen_matrix = np.random.random((3, 3))
print(F"Matrix: ->\n{sixteen_matrix}")
sixteen_vector = np.sum(sixteen_matrix, axis=1)
print(F"Vector: ->\n{sixteen_vector}")

Matrix: ->
[[0.7654605  0.26069798 0.89211205]
 [0.07594857 0.19926062 0.94007644]
 [0.96108764 0.98506029 0.71631722]]
Vector: ->
[1.91827052 1.21528563 2.66246515]


In [29]:
#17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
seventeen = np.random.randint(1, 1000,size=(3,4))
print(F"Matrix: ->\n{seventeen}")
print(F"Matrix with squares of numbers: ->\n{np.square(seventeen)}")

Matrix: ->
[[296 979 531 432]
 [590 744  96 668]
 [382  99 645 116]]
Matrix with squares of numbers: ->
[[ 87616 958441 281961 186624]
 [348100 553536   9216 446224]
 [145924   9801 416025  13456]]


In [4]:
#18 Створіть вектор розміром 4,
# заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
eighteen_vector = np.random.randint(1, 51,size=(4))
print(F"Vector: ->\n{eighteen_vector}")
print(F"Vector with square roots of numbers: ->\n{np.sqrt(eighteen_vector)}")

Vector: ->
[15  2 47 27]
Vector with square roots of numbers: ->
[3.87298335 1.41421356 6.8556546  5.19615242]
