<a href="https://colab.research.google.com/github/Nniikkoollaass/data-science-HW/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
#1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
#3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
n = np.random.randint(1, 10,size=(5,5))
print(n)

[[7 5 8 6 9]
 [4 1 1 7 3]
 [9 4 5 7 3]
 [5 6 2 8 5]
 [3 6 3 3 8]]


In [6]:
#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
b = np.random.random((4, 4))
print(b)

[[0.33573612 0.11337823 0.50378426 0.22984689]
 [0.34913405 0.94502533 0.31728239 0.45928374]
 [0.95124144 0.80793383 0.58385747 0.88621472]
 [0.35377742 0.20999237 0.25640996 0.57822811]]


In [14]:
#5 Створіть два одновимірних масиви розміром 5,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 10
#та виконайте на них поелементні операції додавання, віднімання та множення.
five_one = np.random.randint(1, 10,size=5)
five_two = np.random.randint(1, 10,size=5)
print(f"First -\n {five_one}")
print(f"Second -\n {five_two}")
print(f"Addition: ->\n {five_one + five_two}")
print(f"Subtraction: ->\n {five_one - five_two}")
print(f"Multiplication: ->\n {five_one * five_two}")

First -
 [3 9 8 2 6]
Second -
 [4 5 3 6 2]
Addition: ->
 [ 7 14 11  8  8]
Subtraction: ->
 [-1  4  5 -4  4]
Multiplication: ->
 [12 45 24 12 12]


In [16]:
#6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
six_one = np.random.randint(1, 10,size=7)
six_two = np.random.randint(1, 10,size=7)
print(f"First -\n {six_one}")
print(f"Second -\n {six_two}")
print(f"Scalar product: ->\n {np.dot(six_one, six_two)}")

First -
 [3 8 5 9 1 1 1]
Second -
 [7 6 6 6 6 6 4]
Scalar product: ->
 169


In [13]:
#7 Створіть дві матриці розміром 2x2 та 2x3,
# заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
seven_one = np.random.randint(1, 10,size=(2,2))
seven_two = np.random.randint(1, 10,size=(2,3))
print(f"First -\n {seven_one}")
print(f"Second -\n {seven_two}")
print(f"Matrix multiplication: ->\n{np.dot(seven_one, seven_two)}")

First -
 [[5 8]
 [9 1]]
Second -
 [[9 9 6]
 [2 7 3]]
Matrix multiplication: ->
[[ 61 101  54]
 [ 83  88  57]]


In [17]:
#8 Створіть матрицю розміром 3x3,
#заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
eight = np.random.randint(1, 10,size=(3,3))
print(eight)
eight_inv = np.linalg.inv(eight)
print(f"Inverse matrix: -> \n{eight_inv}")

[[8 5 9]
 [7 3 3]
 [5 6 2]]
Inverse matrix: -> 
[[-0.07894737  0.28947368 -0.07894737]
 [ 0.00657895 -0.19078947  0.25657895]
 [ 0.17763158 -0.15131579 -0.07236842]]


In [18]:
#9 Створіть матрицю розміром 4x4,
# заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
nine = np.random.random((4, 4))
print(nine)
nine_transposed = nine.T
print(f"Transposed matrix: -> \n{nine_transposed}")

[[0.70574818 0.02034391 0.82324456 0.61660955]
 [0.14151298 0.85599133 0.78593336 0.10069257]
 [0.01996414 0.84265245 0.95743033 0.97746369]
 [0.75602607 0.78714933 0.61145705 0.45329291]]
Transposed matrix: -> 
[[0.70574818 0.14151298 0.01996414 0.75602607]
 [0.02034391 0.85599133 0.84265245 0.78714933]
 [0.82324456 0.78593336 0.95743033 0.61145705]
 [0.61660955 0.10069257 0.97746369 0.45329291]]


In [20]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
ten_matrix = np.random.randint(1, 10,size=(3,4))
print(F"Matrix: ->\n{ten_matrix}")
ten_vector = np.random.randint(1, 10,size=(1,4))
print(F"Vector: ->\n{ten_vector}")
print(f"Multiplication: ->\n {ten_matrix * ten_vector}")

Matrix: ->
[[7 7 9 3]
 [7 4 7 3]
 [8 1 5 6]]
Vector: ->
[[8 8 6 4]]
Multiplication: ->
 [[56 56 54 12]
 [56 32 42 12]
 [64  8 30 24]]


In [21]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3,
# заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
eleven_matrix = np.random.random((2, 3))
print(F"Matrix: ->\n{eleven_matrix}")
eleven_vector = np.random.random((1, 3))
print(F"Vector: ->\n{eleven_vector}")
print(f"Multiplication: ->\n {eleven_matrix * eleven_vector}")

Matrix: ->
[[0.08956973 0.88271681 0.87785037]
 [0.63912643 0.36555977 0.98437555]]
Vector: ->
[[0.9394942  0.8296605  0.19878832]]
Multiplication: ->
 [[0.08415024 0.73235527 0.1745064 ]
 [0.60045558 0.3032905  0.19568236]]


In [22]:
#12 Створіть дві матриці розміром 2x2,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
twelve_matrix = np.random.randint(1, 10,size=(2,2))
print(F"Matrix: ->\n{twelve_matrix}")
twelve_vector = np.random.randint(1, 10,size=(2,2))
print(F"Vector: ->\n{twelve_vector}")
print(f"Elemental multiplication: ->\n {twelve_matrix * twelve_vector}")

Matrix: ->
[[7 7]
 [4 9]]
Vector: ->
[[7 7]
 [6 6]]
Elemental multiplication: ->
 [[49 49]
 [24 54]]


In [25]:
#13 Створіть дві матриці розміром 2x2,
#заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
thirteen_matrix_one = np.random.randint(1, 10,size=(2,2))
print(F"Matrix one: ->\n{thirteen_matrix_one}")
thirteen_matrix_two = np.random.randint(1, 10,size=(2,2))
print(F"Matrix two: ->\n{thirteen_matrix_two}")
print(f"Multiplication: ->\n {np.dot(thirteen_matrix_one, thirteen_matrix_two)}")

Matrix one: ->
[[2 5]
 [6 5]]
Matrix two: ->
[[4 4]
 [1 5]]
Multiplication: ->
 [[13 33]
 [29 49]]


In [26]:
#14 Створіть матрицю розміром 5x5,
#заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
fourteen_matrix = np.random.randint(1, 100,size=(5,5))
print(F"Matrix: ->\n{fourteen_matrix}")
print(F"The sum of matrix elements: ->\n{fourteen_matrix.sum()}")

Matrix: ->
[[80 17 80 17 92]
 [82 85 11 93 24]
 [90 25 84 96  4]
 [11 71 34  2 83]
 [58 19 74 83 51]]
The sum of matrix elements: ->
1366


In [27]:
#15 Створіть дві матриці розміром 4x4,
# заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
fifteen_matrix_one = np.random.randint(1, 10,size=(4,4))
print(F"Matrix one: ->\n{fifteen_matrix_one}")
fifteen_matrix_two = np.random.randint(1, 10,size=(4,4))
print(F"Matrix two: ->\n{fifteen_matrix_two}")
print(F"Subtraction of matrices: ->\n{fifteen_matrix_one - fifteen_matrix_two}")

Matrix one: ->
[[9 2 4 7]
 [8 1 9 8]
 [7 6 2 3]
 [4 3 3 4]]
Matrix two: ->
[[4 7 6 7]
 [8 3 6 6]
 [5 8 9 2]
 [9 7 2 7]]
Subtraction of matrices: ->
[[ 5 -5 -2  0]
 [ 0 -2  3  2]
 [ 2 -2 -7  1]
 [-5 -4  1 -3]]


In [28]:
#16 Створіть матрицю розміром 3x3,
#заповніть її випадковими дійсними числами в діапазоні від 0 до 1
#та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
sixteen_matrix = np.random.random((3, 3))
print(F"Matrix: ->\n{sixteen_matrix}")
sixteen_vector = np.array(
    [[sixteen_matrix[0].sum()],
    [sixteen_matrix[1].sum()],
    [sixteen_matrix[2].sum()]],
    dtype=float)
print(F"Vector: ->\n{sixteen_vector}")

Matrix: ->
[[0.0055525  0.52394024 0.46477578]
 [0.80161315 0.12609144 0.23062015]
 [0.50995465 0.17514218 0.63605573]]
Vector: ->
[[0.99426852]
 [1.15832474]
 [1.32115256]]


In [29]:
#17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
seventeen = np.random.randint(1, 1000,size=(3,4))
print(F"Matrix: ->\n{seventeen}")
print(F"Matrix with squares of numbers: ->\n{np.square(seventeen)}")

Matrix: ->
[[296 979 531 432]
 [590 744  96 668]
 [382  99 645 116]]
Matrix with squares of numbers: ->
[[ 87616 958441 281961 186624]
 [348100 553536   9216 446224]
 [145924   9801 416025  13456]]


In [30]:
#18 Створіть вектор розміром 4,
# заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
eighteen_vector = np.random.randint(1, 50,size=(1,4))
print(F"Vector: ->\n{eighteen_vector}")
print(F"Vector with square roots of numbers: ->\n{np.sqrt(eighteen_vector)}")

Vector: ->
[[ 9  4  2 11]]
Vector with square roots of numbers: ->
[[3.         2.         1.41421356 3.31662479]]
